--INSERT INTO users (id, username, password, email)
--VALUES (01, 'coby', '$2a$12$v0BlAeTMKDvjFEesfZIgHehSfovo7FwwlerbdtBH3.F9SJdI6aif.', 'coby@gmail.com');
--
--INSERT INTO users (id, username, password, email)
--VALUES (02, 'erin', '$2a$12$v0BlAeTMKDvjFEesfZIgHehSfovo7FwwlerbdtBH3.F9SJdI6aif.', 'erin@gmail.com');
--
--INSERT INTO ()
--VALUES ();
--
--
--INSERT INTO ()
--VALUES ();
--
--INSERT INTO ()
--VALUES ();
--
--INSERT INTO ()
--VALUES ();
--
--INSERT INTO ()
--VALUES ();
--
--INSERT INTO ()
--VALUES ();